version: 0.2

phases:
  install:
    commands:
      - # Add your installation commands here
      
  pre_build:
    commands:
      - mkdir python
      - pip install -r python/requirements.txt

  build:
    commands:
      # Create a zip file with the Python packages
      - zip -r demo_python.zip python

      # Upload the zip file to S3
      - aws s3 cp demo_python.zip s3://npj-terraform-state/
